/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Datos.Usuario;
import Utilities.Comunicacion;
import Utilities.Seguridad;
import finalpsp.Constantes;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SealedObject;
import javax.swing.JOptionPane;

/**
 *
 * @author Guille
 */
public class VentanaLogin extends javax.swing.JFrame {

    private Socket servidor;
    private InetAddress dir;
    private PrivateKey clavePrivPropia;
    private PublicKey clavePubAjena;

    public VentanaLogin() throws IOException, NoSuchAlgorithmException, ClassNotFoundException {
        this.dir = InetAddress.getLocalHost();
        this.servidor = new Socket(dir, Constantes.PUERTO);

        //genero mis claves
        KeyPair par = Seguridad.generarClaves();
        PublicKey clavePubPropia = par.getPublic();
        this.clavePrivPropia = par.getPrivate();

        //envio mi clave publica
        Comunicacion.enviarObjeto(servidor, clavePubPropia);

        //recibo la clave pub del servidor
        this.clavePubAjena = (PublicKey) Comunicacion.recibirObjeto(servidor);
        System.out.println("VENTANA LOGIN OK");

        initComponents();
    }

    private boolean vacios() {
        boolean vacios = false;
        if (txtUser.getText().isEmpty() || txtPass.getPassword().length == 0) {
            vacios = true;
        }
        return vacios;
    }

    private byte[] resumirPwd() throws NoSuchAlgorithmException {
        char[] pass = txtPass.getPassword();
        String passStr = new String(pass);

        return Seguridad.resumirPwd(passStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Email:");

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Iniciar sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("¿Aún no tienes cuenta?");

        btnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistro.setText("Registrarse");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtPass)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistro)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnLogin)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnRegistro))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        VentanaRegistro vr;
        try {

            vr = new VentanaRegistro(this.clavePrivPropia,
                    this.clavePubAjena, this.servidor);
            vr.setVisible(true);
            vr.setLocationRelativeTo(null);

        } catch (IOException ex) {
        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            if (!vacios()) {
                //envio la orden de login al servidor
                int orden = 1;
                SealedObject so =Seguridad.cifrar(this.clavePubAjena, orden);
                Comunicacion.enviarObjeto(servidor, so);
                System.out.println("CLIENTE Envio Orden");
                //envio el usuario
                byte[] pass = resumirPwd();
                String pass2 = Seguridad.Hexadecimal(pass);
                Usuario u = new Usuario(txtUser.getText(), pass2);
                
                so = Seguridad.cifrar(clavePubAjena, u);
                Comunicacion.enviarObjeto(servidor, so);
                System.out.println("CLIENTE Envio Usuario");
                //recibo el codigo de respuesta del servidor
                so = (SealedObject) Comunicacion.recibirObjeto(servidor);
                int res = (int) Seguridad.descifrar(clavePrivPropia, so);
                System.out.println("CLIENTE Recibo respuesta");
                
                switch (res) {
                    case 0:
                        so = (SealedObject) Comunicacion.recibirObjeto(servidor);
                        Usuario admin = (Usuario) Seguridad.descifrar(clavePrivPropia, so);
                        JOptionPane.showMessageDialog(null, "ADMIN: " + admin.getNick());
                        VentanaAdmin va = new VentanaAdmin(admin, servidor, clavePrivPropia, clavePubAjena);
                        va.setVisible(true);
                        va.setLocationRelativeTo(null);
                        this.dispose();
                        break;
                    case 1:
                        so = (SealedObject) Comunicacion.recibirObjeto(servidor);
                        Usuario usu = (Usuario) Seguridad.descifrar(clavePrivPropia, so);
                        JOptionPane.showMessageDialog(null, "USUARIO ACTIVO: " + usu.getNick());
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(null, "USUARIO NO ACTIVO");
                        break;
                    case 3:
                        JOptionPane.showMessageDialog(null, "LA PASS NO COINCIDE");
                        break;
                    case 4:
                        JOptionPane.showMessageDialog(null, "NO EXISTE EL EMAIL");
                        break;
                }

            } else {
                JOptionPane.showMessageDialog(null, "Rellena ambos campos");
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException | BadPaddingException ex) {
            Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
