
package vista;

import Datos.Usuario;

/**
 *
 * @author Guille
 */
public class VentanaGustos extends javax.swing.JDialog {

    private Usuario usu;
    
    public VentanaGustos(java.awt.Frame parent, boolean modal, Usuario usu) {
        super(parent, modal);
        this.usu = usu;
        initComponents();
        cargarGustos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sldDeporte = new javax.swing.JSlider();
        sldPolitica = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sldArte = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblArte = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDeporte = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPolitica = new javax.swing.JLabel();
        lblInteres = new javax.swing.JLabel();
        lblRelacion = new javax.swing.JLabel();
        lblThijos = new javax.swing.JLabel();
        lblQHijos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sldDeporte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDeporteStateChanged(evt);
            }
        });

        sldPolitica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPoliticaStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Interés por:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("¿Quiere hijos?:");

        sldArte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldArteStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Interés por el arte:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Pasión por el deporte:");

        lblArte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArte.setText("50");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Interés por la política:");

        lblDeporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDeporte.setText("50");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("¿Tiene hijos?:");

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo1.setText("Preferencias de + Nick ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de relación buscada:");

        lblPolitica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPolitica.setText("50");

        lblInteres.setText("jLabel1");

        lblRelacion.setText("jLabel2");

        lblThijos.setText("jLabel3");

        lblQHijos.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInteres)
                            .addComponent(lblRelacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThijos)
                            .addComponent(lblQHijos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPolitica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldArte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblArte))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDeporte)))
                        .addContainerGap(163, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(lblInteres)
                    .addComponent(lblThijos))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addComponent(lblRelacion)
                    .addComponent(lblQHijos))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeporte)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblArte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sldDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldArte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPolitica)
                                    .addComponent(sldPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDeporteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDeporteStateChanged
        setValuesPrefs();
    }//GEN-LAST:event_sldDeporteStateChanged

    private void sldPoliticaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPoliticaStateChanged
        setValuesPrefs();
    }//GEN-LAST:event_sldPoliticaStateChanged

    private void sldArteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldArteStateChanged
        setValuesPrefs();
    }//GEN-LAST:event_sldArteStateChanged

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArte;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblPolitica;
    private javax.swing.JLabel lblQHijos;
    private javax.swing.JLabel lblRelacion;
    private javax.swing.JLabel lblThijos;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JSlider sldArte;
    private javax.swing.JSlider sldDeporte;
    private javax.swing.JSlider sldPolitica;
    // End of variables declaration//GEN-END:variables

    private void setValuesPrefs() {
        lblArte.setText(sldArte.getValue()+"");
        lblDeporte.setText(sldDeporte.getValue()+"");
        lblPolitica.setText(sldPolitica.getValue()+"");
    }

    private void cargarGustos() {
        String[] interes = {"","Hombres", "Mujeres", "Ambos"};
        String[] relacion = {"", "Seria", "Esporadica"};
        String th = "";
        String qh = "";
        
        if (this.usu.getT_hijos() == 'S') {
            th = "Si";
        }else{
            th = "No";
        }
        
        if (this.usu.getQ_hijos() == 'S') {
            qh = "Si";
        }else{
            qh = "No";
        }
        lblTitulo1.setText("Preferencias de "+ this.usu.getNick());
        lblInteres.setText(interes[this.usu.getInteres()]);
        lblRelacion.setText(relacion[this.usu.getRelacion()]);
        lblQHijos.setText(qh);
        lblThijos.setText(th);
        sldArte.setValue(this.usu.getArte());
        sldDeporte.setValue(this.usu.getDeporte());
        sldPolitica.setValue(this.usu.getPolitica());
        
        sldArte.setEnabled(false);
        sldDeporte.setEnabled(false);
        sldPolitica.setEnabled(false);
        
    }
}
