/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Datos.Usuario;
import Utilities.Comunicacion;
import Utilities.Seguridad;
import java.io.IOException;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SealedObject;
import javax.swing.JOptionPane;

/**
 *
 * @author Guille
 */
public class VentanaPrefs extends javax.swing.JDialog {

    private Socket servidor;
    private PrivateKey clavePrivPropia;
    private PublicKey clavePubAjena;
    private Usuario usu;
    
    
    public VentanaPrefs(java.awt.Frame parent, boolean modal,Usuario usu, Socket servidor, PrivateKey clavePrivPropia, PublicKey clavePubAjena) {
        super(parent, modal);
        this.usu = usu;
        this.servidor = servidor;
        this.clavePrivPropia = clavePrivPropia;
        this.clavePubAjena = clavePubAjena;
        
        initComponents();
        rellenarInfoUsu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblPolitica = new javax.swing.JLabel();
        sldDeporte = new javax.swing.JSlider();
        sldPolitica = new javax.swing.JSlider();
        cbRelacion = new javax.swing.JComboBox<>();
        sldArte = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDeporte = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbTHijos = new javax.swing.JComboBox<>();
        cbQHijos = new javax.swing.JComboBox<>();
        cbInteres = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblArte = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo1.setText("Editar preferencias del usuario");

        lblPolitica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPolitica.setText("50");

        sldDeporte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDeporteStateChanged(evt);
            }
        });

        sldPolitica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPoliticaStateChanged(evt);
            }
        });

        cbRelacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una", "Seria", "Esporádica" }));

        sldArte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldArteStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Pasión por el deporte:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Interés por la política:");

        lblDeporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDeporte.setText("50");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("¿Tienes hijos?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de relación buscada:");

        cbTHijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una", "Si", "No" }));

        cbQHijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una", "Si", "No" }));

        cbInteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una", "Hombres", "Mujeres", "Ambos" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Interés por:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("¿Quieres hijos?");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Interés por el arte:");

        lblArte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArte.setText("50");

        btnAceptar.setText("Modificar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnVolver.setText("Cancelar");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbRelacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblTitulo1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbQHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sldPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sldArte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPolitica)
                            .addComponent(lblArte)
                            .addComponent(lblDeporte))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(cbTHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbQHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeporte, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblArte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lblPolitica, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sldDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(sldPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sldArte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDeporteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDeporteStateChanged
        setValuesPrefs();
    }//GEN-LAST:event_sldDeporteStateChanged

    private void sldPoliticaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPoliticaStateChanged
       setValuesPrefs();
    }//GEN-LAST:event_sldPoliticaStateChanged

    private void sldArteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldArteStateChanged
        setValuesPrefs();
    }//GEN-LAST:event_sldArteStateChanged

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if (somethingChanged()) {
            
            try {
                
                //envio la orden al servidor
                int orden = 0;
                SealedObject so =Seguridad.cifrar(this.clavePubAjena, orden);
                Comunicacion.enviarObjeto(servidor, so);
                
                //envio el usuario
                modUsu();
                so = Seguridad.cifrar(clavePubAjena, this.usu);
                Comunicacion.enviarObjeto(servidor, so);
                
                //recibo el nuevo usuario
                so = (SealedObject) Comunicacion.recibirObjeto(servidor);
                Usuario newU = (Usuario) Seguridad.descifrar(clavePrivPropia, so);
                VentanaUsuario.usu = newU;

                JOptionPane.showMessageDialog(null, "Preferencias actualizadas con éxito.");
                this.dispose();
                
            } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException | BadPaddingException ex) {
                Logger.getLogger(VentanaPrefs.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No has modificado nada.");
        }
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbInteres;
    private javax.swing.JComboBox<String> cbQHijos;
    private javax.swing.JComboBox<String> cbRelacion;
    private javax.swing.JComboBox<String> cbTHijos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArte;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblPolitica;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JSlider sldArte;
    private javax.swing.JSlider sldDeporte;
    private javax.swing.JSlider sldPolitica;
    // End of variables declaration//GEN-END:variables

    private boolean somethingChanged() {
        boolean change = false;
        
        int th = 0;
        int qh = 0;
        
        if (usu.getT_hijos() == 'S') {
            th = 1;
        }else{
            th = 2;
        }
        if (usu.getQ_hijos() == 'S') {
            qh = 1;
        }else{
            qh = 2;
        }
        
        if (cbInteres.getSelectedIndex() != usu.getInteres() ||
            cbRelacion.getSelectedIndex() != usu.getRelacion() ||
            sldArte.getValue() != usu.getArte() ||
            sldDeporte.getValue() != usu.getDeporte() ||
            sldPolitica.getValue() != usu.getPolitica() ||
            cbTHijos.getSelectedIndex() != th ||
            cbQHijos.getSelectedIndex() != qh)
        {
            change = true;
        }
        return change;
    }

    private void rellenarInfoUsu() {
        cbInteres.setSelectedIndex(usu.getInteres());
        cbRelacion.setSelectedIndex(usu.getRelacion());
        if (usu.getT_hijos() == 'S') {
            cbTHijos.setSelectedIndex(1);
        }else{
            cbTHijos.setSelectedIndex(2);
        }
        if (usu.getQ_hijos() == 'S') {
            cbQHijos.setSelectedIndex(1);
        }else{
            cbQHijos.setSelectedIndex(2);
        }
        sldArte.setValue(usu.getArte());
        sldDeporte.setValue(usu.getDeporte());
        sldPolitica.setValue(usu.getPolitica());
        
    }

    private void modUsu() {
        this.usu.setInteres(cbInteres.getSelectedIndex());
        this.usu.setRelacion(cbRelacion.getSelectedIndex());
        if (cbTHijos.getSelectedIndex() == 1) {
            this.usu.setT_hijos('S');
        }else{
            this.usu.setT_hijos('N');
        }
        if (cbQHijos.getSelectedIndex() == 1) {
            this.usu.setQ_hijos('S');
        }else{
            this.usu.setQ_hijos('N');
        }
        this.usu.setArte(sldArte.getValue());
        this.usu.setDeporte(sldDeporte.getValue());
        this.usu.setPolitica(sldPolitica.getValue());
    }
    
    private void setValuesPrefs() {
        lblArte.setText(sldArte.getValue()+"");
        lblDeporte.setText(sldDeporte.getValue()+"");
        lblPolitica.setText(sldPolitica.getValue()+"");
    }
}
