/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Datos.Usuario;
import Utilities.Comunicacion;
import Utilities.Seguridad;
import java.io.IOException;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SealedObject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guille
 */
public class VentanaAdmin extends javax.swing.JFrame {

    private Socket servidor;
    private PrivateKey clavePrivPropia;
    private PublicKey clavePubAjena;
    private Usuario admin;
    public static ArrayList<Usuario> listaAdmins;
    public static ArrayList<Usuario> listaUsuarios;

    public VentanaAdmin(Usuario admin, Socket servidor, PrivateKey clavePrivPropia, PublicKey clavePubAjena) throws IOException, ClassNotFoundException, NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException {
        this.admin = admin;
        this.servidor = servidor;
        this.clavePrivPropia = clavePrivPropia;
        this.clavePubAjena = clavePubAjena;

        initComponents();

        rellenarTablaAdmins();
        rellenarTablaUsuarios();
        System.out.println("ADMINS: " + listaAdmins.size());
        System.out.println("USUARIOS: " + listaUsuarios.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAdmins = new javax.swing.JTable();
        btnAddAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        btnUnableAdmin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnActiveUser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        btnCreateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnEnableAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Email", "Nick"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableAdmins);

        btnAddAdmin.setText("Añadir nuevo administrador");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setText("Eliminar administrador");
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        btnUnableAdmin.setText("Quitar privilegio admin");
        btnUnableAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnableAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnAddAdmin)
                .addGap(27, 27, 27)
                .addComponent(btnDeleteAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnableAdmin)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnableAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administradores", jPanel2);

        btnActiveUser.setText("Activar usuario");
        btnActiveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveUserActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(tableUsers);

        btnCreateUser.setText("Crear usuario");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Eliminar usuario");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnEnableAdmin.setText("Convertir en admin");
        btnEnableAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnActiveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnableAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUser)
                .addGap(59, 59, 59))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnableAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActiveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActiveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveUserActionPerformed

        if (tableUsers.getSelectedColumn() != -1) {
            if (listaUsuarios.get(tableUsers.getSelectedRow()).getActivo() == 0) {
                try {

                    //envio la orden al servidor
                    int orden = 0;
                    SealedObject so = Seguridad.cifrar(clavePubAjena, orden);
                    Comunicacion.enviarObjeto(servidor, so);

                    //selecciono el id del usuario que se va a activar, y lo envio
                    String idUser = listaUsuarios.get(tableUsers.getSelectedRow()).getId();
                    so = Seguridad.cifrar(clavePubAjena, idUser);
                    Comunicacion.enviarObjeto(servidor, so);

                    JOptionPane.showMessageDialog(null, "Usuario activado con éxito");

                    rellenarTablaUsuarios();

                } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException ex) {
                    Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario seleccionado ya esta activado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un usuario");
        }
    }//GEN-LAST:event_btnActiveUserActionPerformed

    private void btnEnableAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableAdminActionPerformed

        if (tableUsers.getSelectedColumn() != -1) {
            if (!checkIsAdmin()) {
                try {

                    //envio la orden al servidor
                    int orden = 1;
                    SealedObject so = Seguridad.cifrar(clavePubAjena, orden);
                    Comunicacion.enviarObjeto(servidor, so);

                    //selecciono el id del usuario que se va a convertir en admin
                    String idUser = listaUsuarios.get(tableUsers.getSelectedRow()).getId();
                    so = Seguridad.cifrar(clavePubAjena, idUser);
                    Comunicacion.enviarObjeto(servidor, so);

                    JOptionPane.showMessageDialog(null, "Usuario convertido en administrador correctamente");

                    rellenarTablaUsuarios();
                    rellenarTablaAdmins();

                } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException ex) {
                    Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario seleccionado ya es administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un usuario");
        }

    }//GEN-LAST:event_btnEnableAdminActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed

        VentanaModAdmin vna = new VentanaModAdmin(0, servidor, clavePrivPropia, clavePubAjena, tableUsers, tableAdmins);
        vna.setVisible(true);
        vna.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed

        if (tableUsers.getSelectedColumn() != -1) {
            try {

                //envio la orden al servidor
                int orden = 2;
                SealedObject so = Seguridad.cifrar(clavePubAjena, orden);
                Comunicacion.enviarObjeto(servidor, so);

                //selecciono el id del usuario que se va a eliminar
                String idUser = listaUsuarios.get(tableUsers.getSelectedRow()).getId();
                so = Seguridad.cifrar(clavePubAjena, idUser);
                Comunicacion.enviarObjeto(servidor, so);
                System.out.println("DELETE ENVIADO");

                JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");

                rellenarTablaUsuarios();
                rellenarTablaAdmins();

            } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException ex) {
                Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnUnableAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnableAdminActionPerformed

        if (tableAdmins.getSelectedColumn() != -1) {

            try {

                //envio la orden al servidor
                int orden = 4;
                SealedObject so = Seguridad.cifrar(clavePubAjena, orden);
                Comunicacion.enviarObjeto(servidor, so);

                //selecciono el id del usuario al que se le va a quitar el privilegio
                String idUser = listaAdmins.get(tableAdmins.getSelectedRow()).getId();
                so = Seguridad.cifrar(clavePubAjena, idUser);
                Comunicacion.enviarObjeto(servidor, so);

                JOptionPane.showMessageDialog(null, "Privilegios eliminados correctamente");

                rellenarTablaAdmins();

            } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException ex) {
                Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un admin");
        }

    }//GEN-LAST:event_btnUnableAdminActionPerformed

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        
        if (tableAdmins.getSelectedColumn() != -1) {

            try {

                //envio la orden al servidor
                int orden = 5;
                SealedObject so = Seguridad.cifrar(clavePubAjena, orden);
                Comunicacion.enviarObjeto(servidor, so);

                //selecciono el id del admin que se va a eliminar
                String idUser = listaAdmins.get(tableAdmins.getSelectedRow()).getId();
                so = Seguridad.cifrar(clavePubAjena, idUser);
                Comunicacion.enviarObjeto(servidor, so);

                JOptionPane.showMessageDialog(null, "Administrador eliminado correctamente");

                rellenarTablaAdmins();

            } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException ex) {
                Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un admin");
        }
        
    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        
        VentanaModAdmin vna = new VentanaModAdmin(1, servidor, clavePrivPropia, clavePubAjena, tableUsers, tableAdmins);
        vna.setVisible(true);
        vna.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnAddAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActiveUser;
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEnableAdmin;
    private javax.swing.JButton btnUnableAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableAdmins;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables

    private void rellenarTablaAdmins() throws IOException, ClassNotFoundException {
        try {

            //SealedObject so = (SealedObject) Comunicacion.recibirObjeto(servidor);
            this.listaAdmins = (ArrayList<Usuario>) Comunicacion.recibirObjeto(servidor);

        } catch (IOException | ClassNotFoundException  ex) {
            Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Email");
        modelo.addColumn("Nick");

        Object[] o = new Object[3];
        for (int i = 0; i < listaAdmins.size(); i++) {
            o[0] = listaAdmins.get(i).getId();
            o[1] = listaAdmins.get(i).getEmail();
            o[2] = listaAdmins.get(i).getNick();
            modelo.addRow(o);
        }
        tableAdmins.setModel(modelo);
        tableAdmins.setDefaultEditor(Object.class, null);

    }

    private void rellenarTablaUsuarios() throws IOException, ClassNotFoundException {

        //SealedObject so = (SealedObject) Comunicacion.recibirObjeto(servidor);
        this.listaUsuarios = (ArrayList<Usuario>) Comunicacion.recibirObjeto(servidor);

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Email");
        modelo.addColumn("Nick");
        modelo.addColumn("Edad");
        modelo.addColumn("Activo");

        Object[] o = new Object[5];
        for (int i = 0; i < listaUsuarios.size(); i++) {
            o[0] = listaUsuarios.get(i).getId();
            o[1] = listaUsuarios.get(i).getEmail();
            o[2] = listaUsuarios.get(i).getNick();
            o[3] = listaUsuarios.get(i).getEdad();
            if (listaUsuarios.get(i).getActivo() == 0) {
                o[4] = false;
            } else {
                o[4] = true;
            }

            modelo.addRow(o);
        }
        tableUsers.setModel(modelo);
        tableUsers.setDefaultEditor(Object.class, null);

    }

    private boolean checkIsAdmin() {
        boolean isAdmin = false;
        for (int i = 0; i < listaAdmins.size(); i++) {
            if (listaAdmins.get(i).getId().equals(listaUsuarios.get(tableUsers.getSelectedRow()).getId())) {
                isAdmin = true;
            }
        }
        return isAdmin;
    }

}
